export const APP_LOAD = "APP_LOAD";
export const REDIRECT = "REDIRECT";
export const ARTICLE_SUBMITTED = "ARTICLE_SUBMITTED";


///////////
////TAG///
//////////

//READ
export const GET_TAG = "GET_TAG";

///////////
//ARTICLE//
//////////

//READ
export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLE_USERNAME = "GET_ARTICLE_USERNAME";
export const GET_ARTICLE_TAG = "GET_ARTICLE_TAG";
export const GET_ARTICLE_BY_TOKEN = "GET_ARTICLE_BY_TOKEN";
export const FAV_ARTICLE = "FAV_ARTICLE";
export const GET_ARTICLE_BY_SLUG = "GET_ARTICLE_BY_SLUG";
export const GET_AUTHOR_FAV_ARTICLE = "GET_AUTHOR_FAV_ARTICLE";
export const GET_ARTICLE_BY_FEED = "GET_ARTICLE_BY_FEED"

//DEL
export const DEL_ARTICLE_BY_SLUG = "DEL_ARTICLE_BY_SLUG";
export const UNFAV_ARTICLE = "UNFAV_ARTICLE";

//CREATE
export const CREATE_ARTICLE = "CREATE_ARTICLE";

//UPDATE
export const UPDATE_ARTICLE = "EDIT_ARTICLE";

//Loading
export const PROFILE_PAGE_UNLOADED = "PROFILE_PAGE_UNLOADED";



///////////
//COMMENT//
//////////

//CREATE
export const CREATE_COMMENT = "CREARE_COMMENT";

//DEL
export const DEL_COMMENT = "DEL_COMMENT";

//READ
export const GET_COMMENTS = "GET_COMMENTS"


///////////
//PROFILE//
//////////


//UPDATE USER
export const UPDATE_USER = "UPDATE_USER";

//CREATE
export const FOL_USER = "FOL_USER";

//DEL
export const UNFOL_USER = "UNFOL_USER";

//READ
export const GET_USER = "GET_USER"

//READ 

export const GET_USER_BY_ID = "GET_USER_BY_ID"


export const HOME_PAGE_UNLOADED = "HOME_PAGE_UNLOADED";


//AUTH

export const LOGIN = "LOGIN";
//saga
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";

export const LOGIN_PAGE_UNLOADED = "LOGIN_PAGE_UNLOADED";
export const REGISTER_PAGE_UNLOADED = "REGISTER_PAGE_UNLOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR_INIT = "AUTH_ERROR_INIT"

// export const ASYNC_START = "ASYNC_START";
// export const ASYNC_END = "ASYNC_END";
// export const EDITOR_PAGE_LOADED = "EDITOR_PAGE_LOADED";
// export const EDITOR_PAGE_UNLOADED = "EDITOR_PAGE_UNLOADED";

//ADD and REMOVE TAG
// export const ADD_TAG = "ADD_TAG";
// export const REMOVE_TAG = "REMOVE_TAG";

export const PROFILE_FAVORITES_PAGE_UNLOADED =
  "PROFILE_FAVORITES_PAGE_UNLOADED";
// export const PROFILE_FAVORITES_PAGE_LOADED = "PROFILE_FAVORITES_PAGE_LOADED";

export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS"
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS"
export const AUTH_ERROR = "AUTH_ERROR"
export const GET_ARTICLE_TAG_OR_SLUG_SUCCESS = "GET_ARTICLE_TAG_OR_SLUG_SUCCESS"
export const UNFAV_ARTICLE_SUCCESS = "UNFAV_ARTICLE_SUCCESS";
export const FAV_ARTICLE_SUCCESS = "FAV_ARTICLE_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS"
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const DEL_COMMENT_SUCCESS = "DEL_COMMENT_SUCCESS";
export const CREARE_COMMENT_SUCCESS = "CREARE_COMMENT_SUCCESS";
export const FOL_USER_SUCCESS = "FOL_USER_SUCCESS" 
export const UNFOL_USER_SUCCESS = "UNFOL_USER_SUCCESS"
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS"
export const GET_AUTHOR_FAV_ARTICLE_SUCCESS = "GET_AUTHOR_FAV_ARTICLE_SUCCESS"
export const GET_ARTICLE_BY_FEED_SUCCESS = "GET_ARTICLE_BY_FEED_SUCCESS"
